apiVersion : apps/v1
kind: Deployment
metadata:
  name: samplewebapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplewebapp
  template:
    metadata:
      labels:
        app: samplewebapp 
    spec:
      containers:
      - name: samplewebapp 
        image: myacrrepo31384924.azurecr.io/myacrrepo31384924:latest
         ports:
         - containerPort: 80
      imagePullSecrets:
      - name: imagepullsecret
